## **DataFrame Operations**

In [50]:
import numpy as np
import pandas as pd

In [51]:
# Creating DataFrame using dictionary
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [52]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [53]:
# Creating DataFrame using List
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [54]:
df2['Name'] # select 1 column

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [55]:
df2[['Name','City']]  #Select multiple column

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [56]:
df2['Gender']= ["Male", "Female","Male","Female"]   # Creating New Column

In [57]:
df2

    Name  Age      City  Salary  Gender
0   John   28  New York   65000    Male
1   Anna   34     Paris   70000  Female
2  Peter   29    Berlin   62000    Male
3  Linda   42    London   85000  Female

In [58]:
df2.drop('Age', axis=1)    #Remove Coloumn Temporary

    Name      City  Salary  Gender
0   John  New York   65000    Male
1   Anna     Paris   70000  Female
2  Peter    Berlin   62000    Male
3  Linda    London   85000  Female

In [59]:
df2

    Name  Age      City  Salary  Gender
0   John   28  New York   65000    Male
1   Anna   34     Paris   70000  Female
2  Peter   29    Berlin   62000    Male
3  Linda   42    London   85000  Female

In [60]:
df2.drop('Age', axis=1, inplace=True)    #Remove Coloumn Permanently

In [61]:
df2

    Name      City  Salary  Gender
0   John  New York   65000    Male
1   Anna     Paris   70000  Female
2  Peter    Berlin   62000    Male
3  Linda    London   85000  Female

In [62]:
df2.drop(['Salary','Gender'], axis=1, inplace=True)    #Remove Multiple Coloumn Permanently

In [63]:
df2

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

## **For Row**

In [64]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [65]:
df.drop(1,axis=0) # Temp Delete Row

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [66]:
df.drop([2,3],axis=0)

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [67]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [68]:
df.drop([2,3],axis=0,inplace=True)

In [69]:
df

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [71]:
df2

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [76]:
df2.loc[1] # Select Single row

Name     Anna
City    Paris
Name: 1, dtype: object

In [77]:
df2.loc[[1,2,0]] # select Multiple Row

    Name      City
1   Anna     Paris
2  Peter    Berlin
0   John  New York

In [78]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns) # Creating Dataframe
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [83]:
df2.loc[[0,1,3]][['Age','City','Salary']]  # Select A Subset Part

   Age      City  Salary
0   28  New York   65000
1   34     Paris   70000
3   42    London   85000

In [88]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [90]:
#Select Only Person Has Age Is > 30 And Live In Paris
df2[(df2['Age']> 30) & (df2['City'] == 'Paris') ]

   Name  Age   City  Salary
1  Anna   34  Paris   70000